import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import autoImports from './.wxt/eslint-auto-imports.mjs';

export default [
	{
		ignores: ['.output/**', '.wxt/**', 'node_modules/**'],
	},
	js.configs.recommended,
	...tseslint.configs.recommended,
	// Teaches ESLint about WXT's auto-imported globals (`browser`,
	// `defineBackground`, …). Generated by `wxt prepare`, driven by
	// `imports.eslintrc` in wxt.config.ts.
	autoImports,
	{
		// Build tooling runs in Node, not in the extension — without this every
		// `process` / `console` reference is a `no-undef` error.
		files: ['scripts/**/*.{js,mjs,ts}'],
		languageOptions: {
			globals: globals.nodeBuiltin,
		},
	},
];
